### ISSUE TITLE
String Literals do not isolate other parse components

### ISSUE THREAD

**Issue by stefansjs** [dannymcgee/vscode-klipper#2]
![Screenshot 2024-11-23 163157](https://github.com/user-attachments/assets/069a73be-7c86-432f-91fa-4b6c1638396e)

Basically the screenshot shows it all. But the parser sees a jinja2 `%}` inside a string and thinks it is an end block. Strings literals should have higher parse priority than jinja2 template parsing.

**Comment by dannymcgee** [comment]
Thanks for the issue report! Would you be willing to share the entire file this came from? It's been a little while since I looked at this repo (or touched my 3D printer, frankly), but looking over the code again, it seems like it should only recognize those `{% %}` braces inside of `gcode:` blocks, so I'm not sure how this could have happened unless the grammar somehow failed to recognize the end condition for a `gcode:` block higher up in the file. But either way, having the entire file on hand would make it much easier to troubleshoot.

**Comment by dannymcgee** [comment]
Ah okay, I see what's happening. (I managed to find my Switchwire configs and inserted your `display_data` block into an arbitrary file.)

So there are two issues here:

1. Basically what I described above: the grammar only recognizes the Jinja templates / scripting syntax inside of `gcode:` blocks, so it's completely ignoring the `{% %}` braces and treating everything inside of that as a generic variable. The GCode grammar is embedded [by this pattern](https://github.com/dannymcgee/vscode-klipper/blob/6c7eaa3f9e7eb2ecc1464136d786612639eda75a/packages/klipper-cfg/src/lib/repository/identifier.ts#L52-L64), and the GCode grammar embeds the "klipper script" grammar [with this pattern](https://github.com/dannymcgee/vscode-klipper/blob/6c7eaa3f9e7eb2ecc1464136d786612639eda75a/packages/klipper-gcode/src/lib/repository/template.ts#L5-L19). You could probably just copy/paste that `template.ts` file into the `klipper-cfg` repository and add an `{ include: "#template" }` somewhere in `packages/klipper-cfg/src/lib/repository/identifier.ts` to get it to recognize those Jinja blocks in more places.
2. It looks like the string-literal handling is completely borked in the base `klipper-cfg` grammar. I'm honestly not sure if it's _always_ been borked or if some VS Code / Oniguruma change broke it, but it's treating any `"` tokens it sees as the entire string instead of including everything within pairs of quotes. The code responsible for that is [here](https://github.com/dannymcgee/vscode-klipper/blob/6c7eaa3f9e7eb2ecc1464136d786612639eda75a/packages/klipper-cfg/src/lib/repository/literals.ts#L14-L33), and I'm guessing the `end` condition is the problem.

**Comment by dannymcgee** [comment]
This should be fixed in v0.2.1, which I just published. Let me know if you run into any other issues!

**Comment by stefansjs** [comment]
Looks like that did fix it. Thank you for the quick turnaround!
